[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
blog = "5LZXDznHg7v8h1TcKRGTkuegLbqikJBQJEdvQyEXAdHC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = 'C:\Users\Admin\.config/solana/id.json'

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

wallet =  C:\Users\Admin\.config\solana\id.json